# Generated by Django 5.1.6 on 2025-03-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('user_id', models.IntegerField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
