# Generated by Django 5.1.6 on 2025-03-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp1', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(max_length=14)),
                ('wallet', models.IntegerField(default=0)),
            ],
        ),
    ]
