# Generated by Django 5.1.6 on 2025-03-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUsers',
        ),
    ]
